export const applications = [
  {
    id: "app-1001",
    company: "BrightForge Labs",
    role: "Junior Frontend Developer",
    location: "Remote",
    status: "Interviewing",
    dateApplied: "2026-07-15",
    salaryRange: "$72k-$86k",
    contact: "Maya Chen",
    nextStep: "Technical screen on August 1",
    source: "LinkedIn",
    notes: "Send portfolio link after the call."
  },
  {
    id: "app-1002",
    company: "CivicTrail",
    role: "Associate Software Engineer",
    location: "Seattle, WA",
    status: "Applied",
    dateApplied: "2026-07-21",
    salaryRange: "$78k-$92k",
    contact: "Recruiting Team",
    nextStep: "Follow up next Monday",
    source: "Company site",
    notes: "Public interest tech. Strong mission fit."
  },
  {
    id: "app-1003",
    company: "Northstar Studio",
    role: "UI Engineer Intern",
    location: "Portland, OR",
    status: "Saved",
    dateApplied: "",
    salaryRange: "$30-$36/hr",
    contact: "",
    nextStep: "Customize resume for design systems experience",
    source: "Referral",
    notes: "Ask Jordan about team culture before applying."
  },
  {
    id: "app-1004",
    company: "Fieldstack",
    role: "Frontend Support Engineer",
    location: "Remote",
    status: "Rejected",
    dateApplied: "2026-06-28",
    salaryRange: "$64k-$76k",
    contact: "Anika Patel",
    nextStep: "",
    source: "Indeed",
    notes: "Good practice interview. They wanted more API experience."
  },
  {
    id: "app-1005",
    company: "Harbor Analytics",
    role: "Product Engineer I",
    location: "Boston, MA",
    status: "Offer",
    dateApplied: "2026-07-02",
    salaryRange: "$82k-$96k",
    contact: "Theo Martin",
    nextStep: "Review benefits packet",
    source: "Networking event",
    notes: "Offer expires August 5."
  },
  {
    id: "app-1006",
    company: "LumenCart",
    role: "Junior React Developer",
    location: "Austin, TX",
    status: "Withdrawn",
    dateApplied: "2026-07-08",
    salaryRange: "$66k-$80k",
    contact: "People Ops",
    nextStep: "",
    source: "Built In",
    notes: "Paused because role shifted toward weekend support."
  }
];
